import path from 'path'
import fs from 'fs'
import process from 'process'
import esbuild from 'esbuild'
import builtins from 'builtin-modules'

const nodeBuiltins = [...builtins, ...builtins.map((m) => `node:${m}`)]

// Dev sync target: the user's test vault plugin dir.
// Override with the OBSIDIAN_AI_VAULT_PLUGIN env var if needed.
const VAULT_PLUGIN_DIR =
  process.env.OBSIDIAN_AI_VAULT_PLUGIN ||
  '/Users/Zhuanz1/obsidian/梦幻岛/.obsidian/plugins/UNagent'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

// On every dev rebuild, copy main.js + static manifest.json/styles.css into the test vault.
const devSyncPlugin = {
  name: 'dev-sync',
  setup(build) {
    build.onEnd((result) => {
      if (prod) return
      if (result.errors.length > 0) return
      try {
        fs.mkdirSync(VAULT_PLUGIN_DIR, { recursive: true })
        for (const file of ['main.js', 'manifest.json', 'styles.css']) {
          if (fs.existsSync(file)) {
            fs.copyFileSync(file, path.join(VAULT_PLUGIN_DIR, file))
          }
        }
        console.log(`[dev-sync] artifacts -> ${VAULT_PLUGIN_DIR}`)
      } catch (err) {
        console.error('[dev-sync] failed:', err.message)
      }
    })
  },
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...nodeBuiltins,
  ],
  format: 'cjs',
  jsx: 'automatic',
  loader: { '.ts': 'ts', '.tsx': 'tsx' },
  inject: [path.resolve('import-meta-url-shim.js')],
  define: {
    'import.meta.url': 'import_meta_url',
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
  },
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  plugins: [devSyncPlugin],
})

if (prod) {
  await context.rebuild()
  process.exit(0)
} else {
  await context.watch()
  console.log(`[dev] watching... sync target: ${VAULT_PLUGIN_DIR}`)
}
